### ISSUE TITLE
about the results

### ISSUE THREAD

**Issue by DuTim** [meettyj/RecipeRec#1]
Hello, author. When I used your code and data to reproduce the results, I found that the results were exceptionally good. I think there may be a problem with your data or code. I can't judge the problem. Can you double check the data or code for possible problems such as data leakage? thank you

![image](https://user-images.githubusercontent.com/50939742/181879118-452dfaf3-138a-41c1-9b27-f35bc5d2d30c.png)

**Comment by meettyj** [comment]
Dear DuTim,

Thank you for your interest in our work. I could not reproduce the issue on my end. Could you please be more specific about it?
